### PR TITLE
Fix all of

### PR DESCRIPTION
**Pull request by samw2k00**

### CODE REVIEW

**Comment by YStrauch** [comment]
Hello!

Thank you for issuing this pull request. Unfortunately, at this stage there is not enough information for me to decide if this fix is appropriate.

As this is a test-driven project, please provide a test that fails with the current code base and succeeds with your fix, so that I can understand what your code is solving. Also please ensure all previous tests are running through.

Thank you!

**Comment by samw2k00** [comment]
Hi @YStrauch 

we are trying to validate the consumer data standard --> https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/slate/source/includes/swagger/cds_banking.yaml


im using the following  

`const accountValidateResult = await bankingValidator.validateModel(sample, 'ResponseBankingAccountById')`

where sample is 

`{
  "data": {
    "accountId": "account-4",
    "creationDate": "2021-06-18",
    "displayName": "John Smith 4",
    "maskedNumber": "xxxxxnt-4",
    "productCategory": "TERM_DEPOSITS",
    "productName": "S4",
    "nickname": "my savings 4",
    "isOwned": true,
    "bsb": "000000",
    "accountNumber": "000004",
    "consentStatus": "CONSENTED"
  },
  "links": { "self": "https://localhost:8701/consents/279/accounts/account-4" }
}`

with existing validator, we will get Schema is corrupted (no schema/type)

**Comment by YStrauch** [comment]
Hi!

You found a mistake where either of $ref and allOf can come first. Your code would not cover extreme cases where these two ping-pong back and forth, so I implemented it differently to your solution.

The latest release fixes the error you found, so I'm closing this pull request.

**Comment by samw2k00** [comment]
thank you so much

**Pull request closed without merging**
